# Generated by Django 2.0.13 on 2020-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='fault',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='note',
            field=models.FloatField(null=True),
        ),
    ]
