# Generated by Django 2.0.13 on 2020-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20201127_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='brands',
            new_name='Brands',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='note',
            new_name='PriceNote',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='address',
        ),
        migrations.AddField(
            model_name='note',
            name='Quality',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='City',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='QualityNote',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='StreetName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='ZipCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
