# Generated by Django 2.0.13 on 2020-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20201128_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('Quality', models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('Price', models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='fault',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='fault',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='Brands',
            new_name='NIP',
        ),
    ]
