# Generated by Django 2.0.13 on 2020-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20201130_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Price',
            field=models.IntegerField(choices=[(1, 1), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Quality',
            field=models.IntegerField(choices=[(1, 1), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
