# Generated by Django 2.0.13 on 2020-11-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_auto_20201130_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='Comment',
        ),
        migrations.AddField(
            model_name='workshop',
            name='Comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.Comment'),
        ),
    ]
