# Generated by Django 2.0.13 on 2020-12-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_auto_20201212_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='newcategory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newcategory',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='author',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='date_posted',
        ),
    ]
