# Generated by Django 2.0.13 on 2020-12-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_auto_20201227_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='Task',
        ),
        migrations.AddField(
            model_name='workshop',
            name='Task',
            field=models.ManyToManyField(to='workshop.Task'),
        ),
    ]
