# Generated by Django 2.0.13 on 2020-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_auto_20201227_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='Comment',
            field=models.ManyToManyField(blank=True, to='workshop.Comment'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='Task',
            field=models.ManyToManyField(blank=True, to='workshop.Task'),
        ),
    ]
